Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: dm-
    SupplierDeployMetadata:
      ArtifactRelation:
        'centos_7_9_x64_20G_alibase_20240403.vhd':
          ArtifactId: artifact-6312bbc1751943678574
          ArtifactVersion: 2
      FileArtifactRelation:
        '{{ computenest::file::dm8 }}':
          # 达梦安装文件超过github允许的最大文件大小，所以不在github中维护
          ArtifactId: artifact-efa5575357b647368b1e
          ArtifactVersion: 1
    TemplateConfigs:
      - Name: single_node
        Url: 'ros_templates/template.yaml'
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: docker compose deploy
    Image: 'resources/icons/service_logo.png'